#! /bin/csh -f
set INCLUDE = /www/cProgram/redisLib
set CSLIB = $INCLUDE/redislib.a
set jemallocLib = $INCLUDE/jemalloc/lib/libjemalloc.a
set LIBRARIES = ($CSLIB $jemallocLib -lX11 -lm)
foreach x ($*)
  if ("x$x" == "x-c") then
    set LIBRARIES = ""
    break
  endif
end
gcc -g -I$INCLUDE $* $LIBRARIES
